#!/bin/bash
APODir=~/
apod=$APODir/apod.jpg
wget $picture -O $apod
picture="http://www.starobserver.org/$(echo "$(curl  https://www.starobserver.org/ | grep -Po "image/.*?.jpg" | sed -e 's/<a href=//g' -e 's/"//g' -e 's/>//g')" | head -n 1)"
# if you set your wallpaper as an image that you then overwrite, linux mint (and maybe others as well) will only partially load the updated image. Therefore the following command changes your wallpaper to a random image in your local backgrounds folder to ensure the updated image will be loaded in full
gsettings set org.gnome.desktop.background picture-uri file://$(ls /usr/share/backgrounds/*/*.jpg | head -1)
#convert $apod -colors 8 -dither FloydSteinberg -scale 2000x2000   $apod.png
gsettings set org.gnome.desktop.background picture-uri file:///$apod.png
 
